name: tester

on: push

jobs:
  test:
    name: test code base
    runs-on: ubuntu-latest
    steps:
        - name: Checkout code
        uses: actions/checkout@v4

        - name: setup node
        uses: actions/setup-node@v4
        with: node-version: "18.17.0"

        - name: install dependencies
        run: npm install

        - name: run jest tests
        run: npm test

        - name: run cypress tests
        run: npx cypress run